name: test.sh
on:
  workflow_dispatch:
  schedule:
    - cron: '39 10 16 * *'
  pull_request:
    branches: [main, release/*]
    paths: ['**.sh', '**.yml']
  push:
    branches: [main, release/*]
    paths: ['**.sh', '**.yml']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: ./test/test.sh
